// <auto-generated />
using System;
using Datingsida.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datingsida.Migrations
{
    [DbContext(typeof(DatingDbContext))]
    [Migration("20210107095745_friendlist")]
    partial class friendlist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Datingsida.Models.FriendList", b =>
                {
                    b.Property<int>("FriendRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserReceiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserSender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FriendRequestID");

                    b.ToTable("Friendlists");
                });

            modelBuilder.Entity("Datingsida.Models.ProfileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFilepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfileModelId")
                        .HasColumnType("int");

                    b.Property<string>("Sexuality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileModelId");

                    b.ToTable("ProfileModel");
                });

            modelBuilder.Entity("Datingsida.Models.ProfileModel", b =>
                {
                    b.HasOne("Datingsida.Models.ProfileModel", null)
                        .WithMany("Userinfo")
                        .HasForeignKey("ProfileModelId");
                });

            modelBuilder.Entity("Datingsida.Models.ProfileModel", b =>
                {
                    b.Navigation("Userinfo");
                });
#pragma warning restore 612, 618
        }
    }
}
